### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by nomssi** [OlegBash599/CallABAP_samples#1]
Syntax errors in program ZLSP012_SHOW04 and include ZLSP012_SHOW04_CLS03
line 32, 44, 67, 362 and 376:	Type "ZCL_LSP010_HTML" is unknown.  (replaced by ZCL_LSP012_HTML)
line 52 and 54: 	Type "ZTLSP010_TVARVC" is unknown.  " (replaced by TVARVC)
Type ztlsp010_tsklist not found

**Comment by OlegBash599** [comment]
Thank you!!!
Corrected please check and approve that it is ok.
The code corrected and uploaded.
Also I have added prerequisite: 
1. ABAP2XLSX need to be imported into the system in initial namespace. https://github.com/sapmentors/abap2xlsx
