### ISSUE TITLE
Activation issue with zcl_lsp010_html and tvarc same like the previous

### ISSUE THREAD

**Issue by sodogan** [OlegBash599/CallABAP_samples#2]
hi Oleg

thanks for the sample code, its great
I tried to download and test however i got activaion issue like before still
i changed the zcl_lsp010_html to zcl_lsp012_html
but what about the type inside the lif_reader interface-   INCLUDE TYPE ztlsp012_tsklist. 
ZLSP012_SHOW04_CLS03 include.

Please let me know 

Thanks alot again

**Comment by OlegBash599** [comment]
The code corrected and I have refreshed it.


Also I have added prerequisite: 
1. ABAP2XLSX need to be imported into the system in initial namespace. https://github.com/sapmentors/abap2xlsx

The structure for the table you ask:
MANDT	MANDT
TASKN	SYINDEX
TASKN_SUB	SYINDEX
DESCR	TEXT40
ONUSER	SYUNAME
STATUS	CHAR2
STATUS_TX	TEXT40
COMMENT_TEXT	TEXT80

could be found here:
https://github.com/OlegBash599/CallABAP_samples/blob/master/src/ztlsp012_tsklist.tabl.xml
